config/routes.rb
Rails.application.routes.draw do
  resources :stocks

  resources :investments

  resources :customers

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :investments, :dependent => :destroy
	has_many :stocks, :dependent => :destroy
end

app/models/investment.rb
class Investment < ActiveRecord::Base
	belongs_to :customer
end

app/models/stock.rb
class Stock < ActiveRecord::Base
	belongs_to :customer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :streetaddress, :city, :state, :zip, :primaryemail, :homephone, :cellphone, :created, :modified)
    end
end

app/controllers/investments_controller.rb
class InvestmentsController < ApplicationController
  before_action :set_investment, only: [:show, :edit, :update, :destroy]

  # GET /investments
  # GET /investments.json
  def index
    @investments = Investment.all
  end

  # GET /investments/1
  # GET /investments/1.json
  def show
  end

  # GET /investments/new
  def new
    @investment = Investment.new
  end

  # GET /investments/1/edit
  def edit
  end

  # POST /investments
  # POST /investments.json
  def create
    @investment = Investment.new(investment_params)

    respond_to do |format|
      if @investment.save
        format.html { redirect_to @investment, notice: 'Investment was successfully created.' }
        format.json { render :show, status: :created, location: @investment }
      else
        format.html { render :new }
        format.json { render json: @investment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /investments/1
  # PATCH/PUT /investments/1.json
  def update
    respond_to do |format|
      if @investment.update(investment_params)
        format.html { redirect_to @investment, notice: 'Investment was successfully updated.' }
        format.json { render :show, status: :ok, location: @investment }
      else
        format.html { render :edit }
        format.json { render json: @investment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /investments/1
  # DELETE /investments/1.json
  def destroy
    @investment.destroy
    respond_to do |format|
      format.html { redirect_to investments_url, notice: 'Investment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_investment
      @investment = Investment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def investment_params
      params.require(:investment).permit(:category, :description, :acquiredvalue, :acquireddate, :recentvalue, :recentdate, :created, :modified)
    end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]

  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params.require(:stock).permit(:stsymbol, :stname, :noshares, :purchaseprice, :datepurchased, :created, :modified)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/investments_helper.rb
module InvestmentsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :streetaddress %><br>
    <%= f.text_area :streetaddress %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_area :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_area :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_area :zip %>
  </div>
  <div class="field">
    <%= f.label :primaryemail %><br>
    <%= f.text_area :primaryemail %>
  </div>
  <div class="field">
    <%= f.label :homephone %><br>
    <%= f.text_area :homephone %>
  </div>
  <div class="field">
    <%= f.label :cellphone %><br>
    <%= f.text_area :cellphone %>
  </div>
  <div class="field">
    <%= f.label :created %><br>
    <%= f.datetime_select :created %>
  </div>
  <div class="field">
    <%= f.label :modified %><br>
    <%= f.datetime_select :modified %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Listing customers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Streetaddress</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Primaryemail</th>
      <th>Homephone</th>
      <th>Cellphone</th>
      <th>Created</th>
      <th>Modified</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.streetaddress %></td>
        <td><%= customer.city %></td>
        <td><%= customer.state %></td>
        <td><%= customer.zip %></td>
        <td><%= customer.primaryemail %></td>
        <td><%= customer.homephone %></td>
        <td><%= customer.cellphone %></td>
        <td><%= customer.created %></td>
        <td><%= customer.modified %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Streetaddress:</strong>
  <%= @customer.streetaddress %>
</p>

<p>
  <strong>City:</strong>
  <%= @customer.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @customer.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @customer.zip %>
</p>

<p>
  <strong>Primaryemail:</strong>
  <%= @customer.primaryemail %>
</p>

<p>
  <strong>Homephone:</strong>
  <%= @customer.homephone %>
</p>

<p>
  <strong>Cellphone:</strong>
  <%= @customer.cellphone %>
</p>

<p>
  <strong>Created:</strong>
  <%= @customer.created %>
</p>

<p>
  <strong>Modified:</strong>
  <%= @customer.modified %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/investments/_form.html.erb
<%= form_for(@investment) do |f| %>
  <% if @investment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@investment.errors.count, "error") %> prohibited this investment from being saved:</h2>

      <ul>
      <% @investment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_area :category %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :acquiredvalue %><br>
    <%= f.number_field :acquiredvalue %>
  </div>
  <div class="field">
    <%= f.label :acquireddate %><br>
    <%= f.number_field :acquireddate %>
  </div>
  <div class="field">
    <%= f.label :recentvalue %><br>
    <%= f.number_field :recentvalue %>
  </div>
  <div class="field">
    <%= f.label :recentdate %><br>
    <%= f.datetime_select :recentdate %>
  </div>
  <div class="field">
    <%= f.label :created %><br>
    <%= f.datetime_select :created %>
  </div>
  <div class="field">
    <%= f.label :modified %><br>
    <%= f.datetime_select :modified %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/investments/edit.html.erb
<h1>Editing investment</h1>

<%= render 'form' %>

<%= link_to 'Show', @investment %> |
<%= link_to 'Back', investments_path %>

app/views/investments/index.html.erb
<h1>Listing investments</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Description</th>
      <th>Acquiredvalue</th>
      <th>Acquireddate</th>
      <th>Recentvalue</th>
      <th>Recentdate</th>
      <th>Created</th>
      <th>Modified</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @investments.each do |investment| %>
      <tr>
        <td><%= investment.category %></td>
        <td><%= investment.description %></td>
        <td><%= investment.acquiredvalue %></td>
        <td><%= investment.acquireddate %></td>
        <td><%= investment.recentvalue %></td>
        <td><%= investment.recentdate %></td>
        <td><%= investment.created %></td>
        <td><%= investment.modified %></td>
        <td><%= link_to 'Show', investment %></td>
        <td><%= link_to 'Edit', edit_investment_path(investment) %></td>
        <td><%= link_to 'Destroy', investment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Investment', new_investment_path %>

app/views/investments/new.html.erb
<h1>New investment</h1>

<%= render 'form' %>

<%= link_to 'Back', investments_path %>

app/views/investments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @investment.category %>
</p>

<p>
  <strong>Description:</strong>
  <%= @investment.description %>
</p>

<p>
  <strong>Acquiredvalue:</strong>
  <%= @investment.acquiredvalue %>
</p>

<p>
  <strong>Acquireddate:</strong>
  <%= @investment.acquireddate %>
</p>

<p>
  <strong>Recentvalue:</strong>
  <%= @investment.recentvalue %>
</p>

<p>
  <strong>Recentdate:</strong>
  <%= @investment.recentdate %>
</p>

<p>
  <strong>Created:</strong>
  <%= @investment.created %>
</p>

<p>
  <strong>Modified:</strong>
  <%= @investment.modified %>
</p>

<%= link_to 'Edit', edit_investment_path(@investment) %> |
<%= link_to 'Back', investments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eproj2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/stocks/_form.html.erb
<%= form_for(@stock) do |f| %>
  <% if @stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% @stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :stsymbol %><br>
    <%= f.text_area :stsymbol %>
  </div>
  <div class="field">
    <%= f.label :stname %><br>
    <%= f.text_area :stname %>
  </div>
  <div class="field">
    <%= f.label :noshares %><br>
    <%= f.number_field :noshares %>
  </div>
  <div class="field">
    <%= f.label :purchaseprice %><br>
    <%= f.number_field :purchaseprice %>
  </div>
  <div class="field">
    <%= f.label :datepurchased %><br>
    <%= f.datetime_select :datepurchased %>
  </div>
  <div class="field">
    <%= f.label :created %><br>
    <%= f.text_area :created %>
  </div>
  <div class="field">
    <%= f.label :modified %><br>
    <%= f.text_area :modified %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing stock</h1>

<%= render 'form' %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<h1>Listing stocks</h1>

<table>
  <thead>
    <tr>
      <th>Stsymbol</th>
      <th>Stname</th>
      <th>Noshares</th>
      <th>Purchaseprice</th>
      <th>Datepurchased</th>
      <th>Created</th>
      <th>Modified</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td><%= stock.stsymbol %></td>
        <td><%= stock.stname %></td>
        <td><%= stock.noshares %></td>
        <td><%= stock.purchaseprice %></td>
        <td><%= stock.datepurchased %></td>
        <td><%= stock.created %></td>
        <td><%= stock.modified %></td>
        <td><%= link_to 'Show', stock %></td>
        <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
        <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock', new_stock_path %>

app/views/stocks/new.html.erb
<h1>New stock</h1>

<%= render 'form' %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Stsymbol:</strong>
  <%= @stock.stsymbol %>
</p>

<p>
  <strong>Stname:</strong>
  <%= @stock.stname %>
</p>

<p>
  <strong>Noshares:</strong>
  <%= @stock.noshares %>
</p>

<p>
  <strong>Purchaseprice:</strong>
  <%= @stock.purchaseprice %>
</p>

<p>
  <strong>Datepurchased:</strong>
  <%= @stock.datepurchased %>
</p>

<p>
  <strong>Created:</strong>
  <%= @stock.created %>
</p>

<p>
  <strong>Modified:</strong>
  <%= @stock.modified %>
</p>

<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>